### ISSUE TITLE
Unable to fetch public images

### ISSUE THREAD

**Issue by subodh-dharma** [remore/dockerfileview#6]
I am trying to fetch the `nginx:alpine` image. It is a public image.

I am getting the following error.

```
ubuntu@ubuntu-xenial:~/dockerfileview/dockerfileview$ ./dockerfile nginx:alpine

#
# 🐳  nginx:alpine
#

Failed to fetch nginx:alpine

#
# 🐳  (Direct Input from CLI)
#

FROM nginx:alpine
```
`

**Comment by tholu** [comment]
Same problem here. Would love to use this tool.

**Comment by firozkhan12** [comment]
Same problem here. Would love to use this tool.

**Comment by rezen** [comment]
https://gist.github.com/rezen/964afdf73c7334e8a1b3dffa7b0f7bfa

**Comment by subodh-dharma** [comment]
The script provided by @rezen can be used instead. Closing the issue.
